### ISSUE TITLE
❤

### ISSUE THREAD

**Issue by halkeye** [SwampDragons/packer-provisioner-comment#3]
Had a moment of WHOA when I came across this. Long time no see @SwampDragons .

Just wanted to say hi and i like when I see people I know on the internet.

🌊

**Comment by SwampDragons** [comment]
Hah! Hi Gavin. Hope things are well 😄 Curious what bizarre pathway brought you to this repo, but glad to see you here.

**Comment by halkeye** [comment]
I'm trying to make a windows image to run in the cloud, so poking around with packer. Found someone had a windows update packer plugin which works really well, so went to look what other plugins existed.

**Comment by SwampDragons** [comment]
Oh yeah that one by rgl is great!
